"updates":
- "directory": "/"
  "groups":
    "github-actions":
      "exclude-patterns": []
      "patterns":
      - "*"
  "open-pull-requests-limit": 10
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "daily"
    "time": "04:00"
"version": 2
