name: "Tests for this repo"
on:
  workflow_call:

jobs:
  success_tests:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/success"
      rust_toolchain: ${{ matrix.rust_toolchain }}

  success_lints:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_lints.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/success"
      rust_toolchain: ${{ matrix.rust_toolchain }}

  # Test jobs that expect failure:
  lint_failure_clippy:
    uses: "./.github/workflows/_internal_expected_lint_failure.yml"
    with:
      expected_failure: clippy
      manifest_dir: "tests/clippy-failure"

  lint_failure_fmt:
    uses: "./.github/workflows/_internal_expected_lint_failure.yml"
    with:
      expected_failure: fmt
      manifest_dir: "tests/fmt-failure"

  test_failure_nightly:
    uses: "./.github/workflows/_internal_expected_test_failure.yml"
    with:
      manifest_dir: tests/failure
      rust_toolchain: nightly

  test_failure_stable:
    uses: "./.github/workflows/_internal_expected_test_failure.yml"
    with:
      manifest_dir: tests/failure
      rust_toolchain: stable
