name: Internal job invocation that expects a test failure result
on:
  workflow_call:
    inputs:
      manifest_dir:
        description: Directory containing the Cargo.toml manifest
        required: false
        type: string
        default: .
      rust_toolchain:
        description: Version of the rust toolchain to run against
        required: false
        type: string
        default: stable
      cargo_test_args:
        description: "Arguments to pass to `cargo test` in the test step"
        required: false
        type: string

jobs:
  tests:
    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
    with:
      manifest_dir: ${{inputs.manifest_dir}}
      rust_toolchain: ${{inputs.rust_toolchain}}
      cargo_test_args: ${{inputs.cargo_test_args}}
      _internal_continue_on_error: true

  expect_test_failure:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: transform expected failure
        id: expected_failure
        env:
          NEEDS_JSON: ${{toJSON(needs)}}
          JQ_FAIL_PROGRAM: >
            .tests.outputs["_internal_tests_result"] == "failure"
        run: >
          echo "did_fail=$(echo "$NEEDS_JSON" | jq -r "$JQ_FAIL_PROGRAM")" | tee -a $GITHUB_OUTPUT
      - name: expect failure
        run: exit 1
        if: steps.expected_failure.outputs.did_fail != 'true'
