name: "Tests for this repo"
on:
  workflow_call:

jobs:
  success_tests:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
    secrets: inherit
    with:
      cargo_test_args: "--manifest-path tests/success/Cargo.toml"
      rust_toolchain: ${{ matrix.rust_toolchain }}

  # Test jobs that expect failure; note that these need to be named
  # exactly after the _internal_<test job>_result output.
  failure_tests:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/failure"
      rust_toolchain: ${{ matrix.rust_toolchain }}
      _internal_continue_on_error: true

  failure_fmt:
    uses: "./.github/workflows/ci_baseline_rust_lints.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/fmt-failure"
      _internal_continue_on_error: true

  failure_clippy:
    uses: "./.github/workflows/ci_baseline_rust_lints.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/lint-failure"
      _internal_continue_on_error: true

  all_failure_tests:
    runs-on: ubuntu-latest
    needs:
      - failure_tests
      - failure_fmt
      - failure_clippy
    steps:
      - name: transform the outcomes
        id: outcomes
        env:
          NEEDS_JSON: ${{toJSON(needs)}}
        run: >
          echo "any_success=$(echo "$NEEDS_JSON" | jq '. | to_entries | map({value: .value, key: (.key | sub("^failure_"; ""))}) | map(.value.outputs["_internal_" + .key + "_result"] == "failure") | all')" >>$GITHUB_OUTPUT
      - name: debug
        env:
          OUTCOMES: ${{toJSON(steps.outcomes)}}
        run: echo $OUTCOMES
      - name: failure
        run: exit 1
        if: steps.outcomes.outputs.any_success == 'false'
