name: "Tests for this repo"
on:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  success_tests:
    strategy:
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
    with:
      cargo_test_args: "--manifest-path tests/success/Cargo.toml"
      rust_toolchain: ${{ matrix.rust_toolchain }}

  failure_tests:
    # strategy:
    #   matrix:
    #     rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
    with:
      cargo_test_args: "--manifest-path tests/failure/Cargo.toml"
      rust_toolchain: stable # ${{ matrix.rust_toolchain }}
      _internal_continue_on_error: true

  all_failure_tests:
    runs-on: ubuntu-latest
    needs:
      - failure_tests
    steps:
      - name: transform the outcomes
        run: >
          echo '${{toJSON(needs)}}'
      - name: failure
        run: false
        if: needs.failure_tests.outputs._internal_test_result == 'success'
