name: "Tests for this repo"
on:
  workflow_call:

jobs:
  success_tests:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/success"
      rust_toolchain: ${{ matrix.rust_toolchain }}

  success_lints:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_lints.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/success"
      rust_toolchain: ${{ matrix.rust_toolchain }}

  # Test jobs that expect failure:
  failing_lints:
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        lint:
          - clippy
          - fmt
    runs-on: ubuntu-latest
    steps:
      - name: Start ${{matrix.lint}} run
        uses: ./.github/workflows/_internal_expected_lint_failure.yml"
        with:
          expected_failure: ${{matrix.lint}}
          manifest_dir: "tests/${{matrix.lint}}-failure"

  failing_tests:
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain:
          - nightly
          - stable
    runs-on: ubuntu-latest
    steps:
      - name: Start ${{matrix.rust_toolchain}} test run
        uses: ./.github/workflows/_internal_expected_test_failure.yml"
        with:
          manifest_dir: tests/failure
          rust_toolchain: ${{matrix.rust_toolchain}}
