name: "Tests for this repo"
on:
  workflow_call:

jobs:
  success_tests:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_tests.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/success"
      rust_toolchain: ${{ matrix.rust_toolchain }}

  success_lints:
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: ["stable", "nightly"]
    uses: "./.github/workflows/ci_baseline_rust_lints.yml"
    secrets: inherit
    with:
      manifest_dir: "tests/success"
      rust_toolchain: ${{ matrix.rust_toolchain }}

  # Test jobs that expect failure:
  failing_lints:
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        lint:
          - clippy
          - fmt
    runs-on: ubuntu-latest
    steps:
      - name: Start ${{matrix.lint}} run
        uses: aurelien-baudet/workflow-dispatch@v2
        id: workflow_start
        with:
          workflow: _internal_expected_lint_failure.yml
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          inputs: '{"expected_failure": "${{matrix.lint}}", "manifest_dir": "tests/${{matrix.lint}}-failure"}'
          token: ${{github.token}}
          wait-for-completion-interval: 20s
          workflow-logs: print

  failing_tests:
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain:
          - nightly
          - stable
    runs-on: ubuntu-latest
    steps:
      - name: Start ${{matrix.rust_toolchain}} test run
        uses: aurelien-baudet/workflow-dispatch@v2
        id: workflow_start
        with:
          workflow: _internal_expected_test_failure.yml
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          inputs: '{"manifest_dir": "tests/failure", "rust_toolchain": "${{matrix.rust_toolchain}}"}'
          token: ${{github.token}}
          wait-for-completion-interval: 20s
          workflow-logs: print
