name: "CI/Rust - lints"
on:
  workflow_call:
    inputs:
      manifest_dir:
        description: "Directory containing the Cargo.toml of the codebase under test"
        type: string
        default: "."
      rust_toolchain:
        description: "Rust toolchain to use"
        type: string
        default: stable
      cargo_clippy_args:
        description: "Arguments to pass to `cargo clippy`"
        type: string
        default: "-- -D warnings"

      # Used for testing this repo:
      _internal_continue_on_error:
        description: "Whether to set continue-on-error on the job; set this to true only in the tests _inside this repo_. Otherwise your workflow run will pass when it shouldn't."
        type: boolean

    outputs:
      _internal_fmt_result:
        description: "Result of the test job"
        value: ${{ jobs.cargo_fmt.outputs.result }}
      _internal_clippy_result:
        description: "Result of the test job"
        value: ${{ jobs.cargo_clippy.outputs.result }}
      _internal_deny_result:
        description: "Result of the test job"
        value: ${{ jobs.cargo_deny.outputs.result }}

env:
  CARGO_MANIFEST_DIR: ${{inputs.manifest_dir}}

jobs:
  cargo_fmt:
    runs-on: ubuntu-latest
    continue-on-error: ${{inputs._internal_continue_on_error}}
    outputs:
      result: ${{steps.fmt.outcome}}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{inputs.rust_toolchain}}
      - name: "cargo fmt"
        id: fmt
        run: "cargo fmt -v -- --check"

  cargo_clippy:
    runs-on: ubuntu-latest
    continue-on-error: ${{inputs._internal_continue_on_error}}
    outputs:
      result: ${{steps.clippy.outcome}}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{inputs.rust_toolchain}}
      - uses: giraffate/clippy-action@v1
        id: clippy
        with:
          reporter: "github-pr-review"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: ${{inputs.cargo_clippy_args}}

  cargo_deny:
    runs-on: ubuntu-latest
    continue-on-error: ${{inputs._internal_continue_on_error}}
    outputs:
      result: ${{steps.deny.outcome}}
    steps:
      - uses: actions/checkout@v3
      - name: Check deny.toml
        id: configured
        uses: andstor/file-existence-action@v2
        with:
          files: "deny.toml"
      - name: "cargo deny"
        id: deny
        if: steps.configured.outputs.files_exists == 'true'
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: "check all"
